name: Update Data

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Paso 1 Checkout repo
        uses: actions/checkout@v4

      - name: Paso 2 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Paso 3 - crea entorno virtual
        run: python -m venv venv

      - name: Paso 4 - activar entorno virtual
        shell: powershell
        run: .\venv\Scripts\Activate.ps1

      - name: Paso 5 - actualizar pip
        run: .\venv\Scripts\python.exe -m pip install --upgrade pip

      - name: Paso 6 - instalar dependencias desde requirements.txt
        run: .\venv\Scripts\python.exe -m pip install -r requirements/requirements.txt

      - name: Paso 7 - Ejecutar Script
        run: .\venv\Scripts\python.exe prueba.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Primera entrega action, segunda entrega action
          commit_user_name: Carlos Alberto Velez M [GitHub Actions]
          commit_user_email: carlos.velez51@iudigital.edu.co
          commit_author: Carlos Alberto Velez M <carlos.velez51@iudigital.edu.co>
